### ISSUE TITLE
Yarn run fail

### ISSUE THREAD

**Issue by lollofra** [muety/mininote#61]
I've tried to install mininote with yarn but it give me this error:
![Schermata del 2021-01-09 18-37-09](https://user-images.githubusercontent.com/17254822/104104655-be43d800-52a9-11eb-9608-0a5576f998d9.png)

Some info about my config:
SO: CentOS Stream 8
NodeJS: 14.15.4
Yarn: 1.22.5

**Comment by muety** [comment]
Thanks for the feedback! Should be fixed now, please try again.

**Comment by lollofra** [comment]
Thank you, now all works fine! 
PS: I've sent you a coffee :coffee:

**Comment by lollofra** [comment]
Just another question, there is a suggested configuration sample to use for nginx?

**Comment by muety** [comment]
> Thank you, now all works fine!
> PS: I've sent you a coffee coffee

Thanks a lot, I'll enjoy it :coffee: 



> Just another question, there is a suggested configuration sample to use for nginx?

Not yet, but check out [this link](https://traggo.net/reverse-proxy/). It gives reverse proxy examples for a different tool, but they should apply to MiniNote more or less equally.
