### ISSUE TITLE
`window.crypto.subtle` is undefined when saving note

### ISSUE THREAD

**Issue by plmdie** [muety/mininote#73]
Hi, as the title says i get this error when trying to save a note.
Tried to run in docker and with yarn, same result.
Thanks in advance

**Comment by muety** [comment]
What browser (and version) are you using?

**Comment by plmdie** [comment]
Firefox 97.0

**Comment by muety** [comment]
That's weird, I can't reproduce that error. Can you please show a screenshot of your DevTool's console? And can you please try in a different browser and / or incognito window?

**Comment by plmdie** [comment]
here:
![image](https://user-images.githubusercontent.com/100805793/156462442-5b4f71f9-35ad-4bc2-8ae6-9aa78ff02be0.png)

**Comment by plmdie** [comment]
Tried Brave browser, different error.
Screenshot:
![image](https://user-images.githubusercontent.com/100805793/156467098-c2377e6e-1f15-416b-8d78-6066a4677c42.png)

**Comment by muety** [comment]
Can you please try whether the demo instance (link in the readme) is working for you?

**Comment by plmdie** [comment]
Yes, it works fine.

**Comment by muety** [comment]
Alright, so I learned that `window.crypto.subtle` is indeed intended to be undefined when not serving the page via HTTPS.

* https://developer.mozilla.org/en-US/docs/Web/API/Crypto/subtle
* https://github.com/w3c/webcrypto/issues/28

Didn't know about that, so thanks for bringing this up! 

I guess the only solution for you would then be to use TLS encryption (with a self-signed cert), as described at https://github.com/muety/mininote#use-https-for-backend.

**Comment by plmdie** [comment]
Ok, thanks for checking that up for me, can you just explain me this step?

-Launch the backend server -> To switch back to the HTTP server, nullify either field and relaunch again.

Thanks once again

**Comment by muety** [comment]
Yes, so first, create a certificate (and private key), as described [here for Linux](https://www.linode.com/docs/guides/create-a-self-signed-tls-certificate/) (for Windows, best use the Linux subsystem to create the cert and then copy over the files to your Windows filesystem). Then point the two `HTTPS_*` variables in `config.js` to the respective files. To disable HTTPS again, clear one or both.

**Comment by plmdie** [comment]
Ok, i'm already using Ubuntu, and i'm aware of the procedure for creating the certificate, it was just the "nullify either field" that i didn't got.
Thanks a lot for the quick replies.
Mininote will make a nice addition to my server app package!!

**Comment by plmdie** [comment]
I don't know if i should open another issue, but if you say so i'll do it.
Everything is working fine with SSL certificate but i've run into another issue, when on Android, there's no save icon, so it's impossible to save notes.

**Comment by muety** [comment]
Please open another issue, preferably with OS- and browser version and a screenshot.
