### ISSUE TITLE
Delete Notebook

### ISSUE THREAD

**Issue by ElGranLoky** [muety/mininote#76]
**Version:** 1.0.2
**S.O:** Docker

I can create notebooks, and enter in it, but I can´t delete after.

**Comment by muety** [comment]
Deleting notebooks is in fact not implemented, yet. Should be an easy one, though.

**Comment by ElGranLoky** [comment]
Ok, thanks for the info.

Good work, I wait.

**Comment by BBentleyDev** [comment]
I'd like to work on this but I'm having trouble getting a development environment created. I got the project running on localhost using the instructions in the readme but any changes I make don't have any effect.

I'm new to opensource so any help would be appreciated!

**Comment by muety** [comment]
The instruction in the readme are for building the app for production. For development, you'd rather want to:
1. Start the backend: `yarn dev` (port 3000)
2. Separately start a dev server for the frontend: `yarn dev` inside the `webapp` folder (port 8080)

**Comment by vinmaster** [comment]
Hi, I've created a PR for this feature. Please take a look: https://github.com/muety/mininote/pull/77

**Comment by ElGranLoky** [comment]
Hi @muety ,

Could you make the corresponding release for ghcr.io/muety/mininote that adds the deletion?

In docker the last tag is 1.0.2.

Thanks

**Comment by muety** [comment]
Done!
