### ISSUE TITLE
Make notebooks be accessible via URL

### ISSUE THREAD

**Issue by muety** [muety/mininote#9]
Introduce very basic routing, so that a notebook `recipes` could be directly accessed (and therefore browser-bookmarked) via `https://notes.myserver.ex/recipes`.

**Comment by ibiBgOR** [comment]
I would like to implement the routing. I also started with the routing last week. I'm not done yet and it would lead to some refactoring.

**Comment by n1try** [comment]
@IamRaviTejaG No, actually this should be a frontend-only thing.

**Comment by n1try** [comment]
Requires to introduce [vue-router](https://vuejs.org/v2/guide/routing.html).
